# SPDX-License-Identifier: Apache-2.0
name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    uses: lpasquali/rune-ci/.github/workflows/docs-deploy.yml@72ffc70b5253c30afd47b06e81eff3f9b08c04c8
